### ISSUE TITLE
Way to cancel downloading

### ISSUE THREAD

**Issue by makew0rld** [makew0rld/amfora#129]
There should be a way to cancel downloading without using <kbd>Ctrl-C</kbd> and quitting the entire browser. Could easily be implemented by removing "Downloading..." in favour of a "Cancel" one that would close the connection and delete the file when clicked.

There should also be some text in the modal while the connection is being made, currently it's just the "Downloading..." button and then later the progressbar output appears.

**Comment by guzzisti** [comment]
loosely related:
way to often i end up with closing amfora (with all the open tabs) cause `Ctrl+C` is too familiar to stop a action (e.g. loading a page).

I would really prefer to remap `ctrl+c` to stop loading and only `ctrl+q` for closing amfora right away.

**Comment by makeworld-the-better-one** [comment]
I think the majority of people are familiar with <kbd>Ctrl-C</kbd> stopping an application rather than some subroutine like loading a page. In any case, #57 would have to be closed for stopping page loading to be implemented.

**Comment by guzzisti** [comment]
This may be a bit offtopic in this issue, but i'd like to add:
i agree that `ctrl+c` is a often used shortcut to exit a program in a terminal. 
But too often i end up with closing amfora and loose all of my open tabs as i hit `ctrl+c`. It acts too much like `ctrl+q` if theres a difference at all.

comparison to firefox: it uses `ctrl+c` to cancel page loading and `ctrl+q` for exit

**Comment by makeworld-the-better-one** [comment]
Hmm, I didn't know that about Firefox. In Amfora, the main difference is that <kbd>Ctrl-C</kbd> will quit even if you're in the middle of loading or downloading. The other keys will not. This isn't a great behaviour though, it should probably be changed.

In any case, this isn't being worked on right now, when it ends up getting worked on this can be hashed out further.

**Comment by makew0rld** [comment]
I am closing all stale non-bug issues so this issue will be closed. However a PR for this would still be accepted.
