### ISSUE TITLE
Offline browsing using disk cache

### ISSUE THREAD

**Issue by ploum** [makew0rld/amfora#169]
The lightness of Gemini could allow use for something I find extraordinary: offline browsing!

My conception of it is closely linked to a reading list described in #168.

1. When Amfora is online, every subscription, bookmark and link in the reading list is automatically saved locally in a cache (or updated if a previous version was already present).
2. Optionally, every link in those pages is also saved (with a depth parameter so you could potentially save to depth 2 or 3).
3. When browsing offline, only the cache version are accessed.
4. If following a link not present in the cache, that link is added to the reading list.

Which means that 1) you will not forgot to read it and 2) as soon as amfora is online, even briefly, it will be downloaded.

This feature would be awesome for people with shaky connections, people traveling or people looking for a disconnected/distraction-free environment while still allowing serendipitous reading.

BONUS: if links accessed offline are not Gemini (typically HTTP), they will instead be saved in an external file (like url_to_visit.txt) which means that the user could really easily open them later in her web browser.

**Comment by makeworld-the-better-one** [comment]
Hmm, this is an interesting idea, I like it. I think **4** is an interesting idea, but it requires a reading list which I'm not in favour of currently, as discussed in #168. Perhaps once #56 is implemented Amfora can ask you when you click the link: "Do you want to add this to your Read-it-later bookmarks?" or something. That way it's still working off bookmarks, but you can still do what you've described.

In any case I think offline browsing is a powerful feature, thanks for bringing it up.

**Comment by makew0rld** [comment]
I am closing all stale non-bug issues so this issue will be closed. A PR for this is unlikely to be accepted since Amfora is in maintenance mode and this would be a major change.
