### ISSUE TITLE
Allow searching from the CLI

### ISSUE THREAD

**Issue by ThomasAdam** [makew0rld/amfora#185]
When amfora is started as `amfora foobar`, the argument is passed directly to `display.URL()` which does not have any concept of sanitising the input in the same way that typing a URL/search term would do within `amfora` itself.

The logic used in the search term bar should apply to the argument passed to `amfora` on the command line as well.

**Comment by makeworld-the-better-one** [comment]
I'm not sure how useful this would be. I guess for searching your search engine directly from the command line? But it's pretty easy to also open Amfora, press space, and then search.

A question for implementing this: will multiple CLI arguments be treated as one search separated by spaces? Or will only the first one be looked at, and the search will have to be quoted: `amfora 'my search'`.

**Comment by makew0rld** [comment]
I am closing all stale non-bug issues so this issue will be closed. However a PR for this could still be accepted.
