### ISSUE TITLE
Tab auto-refresh

### ISSUE THREAD

**Issue by takaoni** [makew0rld/amfora#208]
It would be a nice option, if it's technically possible. Maybe by a keybinding to define which refresh rate, from never to every n minute ?

**Comment by makeworld-the-better-one** [comment]
It's definitely technically possible, but I don't really see the point. Why have this? And how are you picturing that keybinding working, how would you set the refresh rate?

**Comment by takaoni** [comment]
The most obvious usecase on my side is subscriptions page, because I have 40~50 updates a day and refreshing it manually is not really handy IMO, but I also think about pages without atom feed but somewhat active, like gemini://geddit.glv.one/, gemini://gemini.bortzmeyer.org/software/lupa/stats.gmi...
About the keybinding, I imagined that each tab could have a property "auto-refresh", a list like [None, 1min, 5min, 15min, 30min, 1h, 6h, 12h, 24h] set to None by default, and each time typing on the key would define the next auto-refresh value on the list. Or maybe having a popup like a status 10 to manually define it would be more handy ?

**Comment by makeworld-the-better-one** [comment]
The actual subscriptions are updated automatically in the background when Amfora is open. You could just reload the subscription page whenever you come back to it. If you want to change how fast Amfora updates you can look into the `[subscriptions]` section of the config. Am I misunderstanding?

**Comment by takaoni** [comment]
This is my point : I have to refresh the subscriptions page manually dozens times a day and I would prefer this job to be done by something else than me... I opened the issue because I thought that it could be useful to have the feature on potentially every page but for my very specific use case, having an auto refresh on the subscriptions page only would be good enough.

**Comment by makeworld-the-better-one** [comment]
This isn't something I'm that interested in implementing, but I'll leave it open for now. If someone submits a well made PR I'll consider it.

**Comment by makew0rld** [comment]
I am closing all stale non-bug issues so this issue will be closed. However a PR for this may still be accepted, although I'm still not really convinced this is a useful feature.
