### ISSUE TITLE
Allow custom URL placement for external handlers

### ISSUE THREAD

**Issue by t-900-a** [makew0rld/amfora#212]
Relevant code: https://github.com/makeworld-the-better-one/amfora/blob/4ecdede58006e77dd23a27b40752103afa6fb989/display/handlers.go#L81

It would be better if the custom commands that are specified in the config could have parameters within them.

Right now the url is concatenated to the end of the specified command.

I.e. instead of appending to the end, all instances of {url_param} are replaced within the url

**Comment by makeworld-the-better-one** [comment]
Could you give me an example use case where having the URL at the end of the command doesn't work?

**Comment by t-900-a** [comment]
> Could you give me an example use case where having the URL at the end of the command doesn't work?

Opening up a new terminal window to display something in a specific application
`
gnome-terminal -- "myprogram --uri %s"`


I don't see a way to display a cli program in a new terminal without having the quotes

I'd definitely be open to any alternatives, if there aren't any would you be willing to accept a pull request with this change?

**Comment by makeworld-the-better-one** [comment]
There might be a way around this, but if you're offering a pull request than I'm happy to merge this and add it. Just make sure you document it in the `default-config.toml` file. I would suggest something like `{{url}}` being the replaced text.

**Comment by makew0rld** [comment]
I am closing all stale non-bug issues so this issue will be closed. However a PR for this could still be accepted.
