### ISSUE TITLE
Tab length with Asian characters

### ISSUE THREAD

**Issue by Salty2021** [makew0rld/amfora#246]
When displayed in amfora, The following source file of a table  with items separated by "tab" characters

```
fruit	vegetable	meat
apple	tomato		fish
사과	토마토		물고기
```
is not correctly aligned:

![](https://user-images.githubusercontent.com/86095544/124288336-a297fb00-db83-11eb-9042-3518b4ac048e.png)

**Comment by makeworld-the-better-one** [comment]
Thanks for reporting this. This is an upstream issue, possibly with cview or tcell. I've created [this](https://code.rocketnine.space/tslocum/cview/issues/63) cview issue to track this. I can't speak to when a fix will happen, as this is out of my hands. Thanks for reporting though.

**Comment by makew0rld** [comment]
Closing this issue:
- It's stale
- It's upstream
- Upstream says it's expected (if not ideal) behaviour
