### ISSUE TITLE
Letting the page-down action pass the end of the content

### ISSUE THREAD

**Issue by nadrad** [makew0rld/amfora#249]
When there's less than one page of content in the current position and I press page down, the page moves less than one page, in a way that the end of the content is positioned at the bottom of the page. The problem is that when I'm reading and reach the bottom of the page, I press page down and scroll my eye back to the top of the page, expecting to continue reading. Then I realize what's happened and I have to scan the page to find where I was before and continue reading from there.

I think it would be much better to let the page-down action pass the end of the content (for maximum one page) and always scroll it exactly one page. Similar to Vim and some other applications, the empty part after the content can be marked with ~, or another symbol.

**Comment by makeworld-the-better-one** [comment]
Good idea, thanks. I would accept a PR for this, or might add it myself eventually.

**Comment by mbs** [comment]
i agree with this, would further like to propose that pagedown always goes a full page down minus one line, including giving blanks at the end as proposed by nadrad.  this should maybe be configurable if there is some population of users that likes the current 75% strategy (or whatever it is).

**Comment by makew0rld** [comment]
I am closing all stale non-bug issues so this issue will be closed. However a PR for this could still be accepted. Thanks!
