### ISSUE TITLE
Ability to run user-defined actions/scripts

### ISSUE THREAD

**Issue by mntn-xyz** [makew0rld/amfora#262]
It would be nice to have a hotkey or bar command to run a user-defined action with the argument being the current URL or the URL of a specific link #. For instance, I might want to append the URL to a text file, use Emacs org-capture to file the URL appropriately, compose a new email with the link in the message body, etc.

**Comment by mntn-xyz** [comment]
True, I wouldn't consider it high priority, but it would save a couple of keystrokes each time, which can add up.

What led me to suggest this is that I like to manage bookmarks in orgmode, as I can annotate, categorize, and tag them appropriately. The bookmarks functionality in Amfora works well enough, but it isn't adequate for my needs. (Not a criticism of Amfora, by the way; Chrome's bookmarks functionality also isn't adequate from my perspective. I have too many bookmarks.)

**Comment by makeworld-the-better-one** [comment]
Definitely some interesting uses there. A PR would be appreciated if the changes aren't too extensive and are documented. Thanks!

**Comment by mntn-xyz** [comment]
Things I didn't add in the PR, but which I considered:
* Automatic substitution of home directory path for ${home} in command path - while this may be useful it's just a nice to have
* Running commands on a specific link from the command bar, like `cmd1:15` to run command 1 on link 15. This could be useful in certain contexts, but honestly it's' not strictly necessary, and I expect people who use this heavily to rebind the keys anyway to sensible mnemonics like "Alt-E" for "email" or similar. In this case they would have to remember that "cmd5" or whatever corresponds to email.

**Comment by makew0rld** [comment]
Fixed by #265. I'll make a new issue for the minor comment I left behind.
