### ISSUE TITLE
Feature request: external editor for input

### ISSUE THREAD

**Issue by codeandcreate** [makew0rld/amfora#268]
At the moment if i want to post something there pops up a small window with a one line input.
Instead of build in a full editor for posting bigger texts to a gemlog (...) it would be nice if i can configure an external editor like vi(m) or nano/micro to take care of the users input and post the resulting temporary text file back to gemini.

**Comment by makeworld-the-better-one** [comment]
Input over Gemini is just really intended to be one line, so I'm not sure if this makes sense.

**Comment by codeandcreate** [comment]
i know but places like midnight.pub or station.martinrue.com (social networking in gemini) will benefit from such a feature

**Comment by makeworld-the-better-one** [comment]
Ok, maybe it makes sense. I don't think it would be very easy (or possible at all) with the current tech stack, but worth looking into.

**Comment by makew0rld** [comment]
I am closing all stale non-bug issues so this issue will be closed. However a PR for this could still be accepted, it's a nice idea.
