### ISSUE TITLE
Resizing doesn't work consistently with Tilix

### ISSUE THREAD

**Issue by makew0rld** [makew0rld/amfora#276]
When using [Tilix](https://gnunn1.github.io/tilix-web/) as a dropdown terminal with Amfora open, oftentimes when it drops down, Amfora only resizes to the height of the non-fullscreen terminal. This is an issue with cview resizing most likely. Unless there is an issue with Amfora handling resize events that come quickly one after another.

**Comment by makeworld-the-better-one** [comment]
After some testing, it seems like this is indeed a cview issue. It is only picking up one resize event when two happen in succession with Tilix.

**Comment by makeworld-the-better-one** [comment]
Filed issue with cview: https://code.rocketnine.space/tslocum/cview/issues/84

**Comment by makew0rld** [comment]
Closing:
- Issue is stale
- Issue is upstream
- I don't use Tilix anymore, I use Wezterm now instead
