### ISSUE TITLE
Add Tab and Shift-Tab to keybindings

### ISSUE THREAD

**Issue by seanicus64** [makew0rld/amfora#295]
In the Linux VT terminal it won't recognize Shift+Tab, and instead interprets it as a Tab.  I was happy when I saw that amfora supports custom keybindings, but not a single one of them appear to relate to selecting the next or previous tab.  This is a curious omission.  Is there something I'm missing, or are these values simply not in the default keybindings file?

**Comment by makeworld-the-better-one** [comment]
Yep, it looks like this is missing from the keybindings. Definitely something that should be added.

**Comment by makew0rld** [comment]
Seems fixed now.
