### ISSUE TITLE
Consider shipping release tarball with vendored dependencies

### ISSUE THREAD

**Issue by illiliti** [makew0rld/amfora#296]
For example, [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy/tree/master/vendor) does this by simply maintaining vendor directory. You can also setup CI to vendor dependencies into release tarball without needing to keep vendor directory within repository. Here is the command that can be used for this: `go mod vendor`

With vendored dependencies, i can build amfora from source without internet connection by using this command: `go build -mod=vendor`

**Comment by makeworld-the-better-one** [comment]
Good idea, thanks. I'll add this for the next release.

**Comment by makeworld-the-better-one** [comment]
PR #299 is one attempt at adding this.

**Comment by aabacchus** [comment]
@makeworld-the-better-one has there been any progress on this? Thanks

**Comment by makeworld-the-better-one** [comment]
Nope I haven't made progress on this. It's still something I'd like to do but not a high priority for me. I made a comment in #299, so if someone made a PR that addresses that comment, I might be able to merge it in.

**Comment by makew0rld** [comment]
Closing this as there will be few feature Amfora releases. However I see the value and so I have manually added a vendored source code tarball to the latest release.
