### ISSUE TITLE
Feed subscription - support text/gemini feeds

### ISSUE THREAD

**Issue by valvin1** [makew0rld/amfora#323]
Amfora supports atom, rss and json feeds but it doesn't support gemini feeds as described here: 

gemini://gemini.circumlunar.space/docs/companion/subscription.gmi

it is a simple `text/gemini` with links in a specific format `=> <link> YYYY-MM-dd - <title>`

an example is available here: 

gemini://gemini.circumlunar.space/news/

At the moment when I subscribe to this page using `CTRL+x` it is not well parsed and appears directly in the feed lists instead of having its links.

**Comment by makew0rld** [comment]
Personally I'm fine the status quo where updates to those pages still appear, just not in a parsed form. But a PR for this could be accepted.
