### ISSUE TITLE
Bind jk to behave as TAB for next/prev URL selection

### ISSUE THREAD

**Issue by wolandark** [makew0rld/amfora#325]
Hi and thanks for Amfora;

It would be great if I could use J and K (capitals, Shift-j and Shift-k) to go back and forth between links and use jk to scroll normally.
Or maybe get URL selection as we scroll with j and k. I think this is how w3m does it.
I looked through the config and I cant see an option to bind URL selection or highlight or anything about the tab key, maybe Im missing something. 
btw Im using the lastest release on Arch

Thanks.

**Comment by makeworld-the-better-one** [comment]
Not sure if this should be the default, but it's at least reasonable for binding this to be possible. Not really working on Amfora at the moment, but would accept a PR for this.
