### ISSUE TITLE
localhost address

### ISSUE THREAD

**Issue by FiskFan1999** [makew0rld/amfora#326]
Currently, if you type "localhost" into the bar, it defaults to a geminispace.info search for that term, as opposed to a direct link with scheme gemini:// if you type a URL such as gemini.circumlunar.space (this happens to me a lot because I enjoy using amfora to test my gemini capsule locally). This doesn't happen if you call `amfora localhost`, because the address in argv is always treated as direct URL. I'm interested in your thoughts on if localhost should also result in a direct link instead of a search. Thank you

**Comment by makeworld-the-better-one** [comment]
Yeah that's fair, I think it makes sense for `localhost` to go to `gemini://localhost/` in the bottom bar. I'm not working on Amfora much these days but would accept a PR for this.

**Comment by FiskFan1999** [comment]
Thanks. Will get on this. Thanks for making amfora by the way.

**Comment by makew0rld** [comment]
Fixed in #327
