### ISSUE TITLE
yes/no dialogue for redirect is confusing since it is not clear what is active

### ISSUE THREAD

**Issue by alexlehm** [makew0rld/amfora#332]
The follow redirect dialogue is confusing for me since it is not clear which button is active. It would be better if the button had some kind of shape change to show which on is selected

![image](https://user-images.githubusercontent.com/156144/225307319-78cc8e67-1de8-4f63-adbd-26dadb032ed1.png)

**Comment by makew0rld** [comment]
Unfortunately I can't change the button shape in the underlying UI library. I hoped that the lighter color signifies the active button. But you're welcome to change the button color using themeing to make it more obvious to you.
