### ISSUE TITLE
How to bind Shift-Space

### ISSUE THREAD

**Issue by varon** [makew0rld/amfora#334]
I would like to have shift-space operate as page up. How can that be done?

**Comment by makew0rld** [comment]
I doubt shift-space will be picked up correctly by your terminal, but using `bind_pgup = "Shift-Space"` would be the line to put in the [config file](https://github.com/makew0rld/amfora/blob/1da658c8a6f2ba34eb919b3e59c07fde02510297/default-config.toml#L112).

https://github.com/makew0rld/amfora/wiki/Configuration
