### ISSUE TITLE
-W option from less

### ISSUE THREAD

**Issue by kovmir** [makew0rld/amfora#344]
Hey, would you be willing to include `-W` option from `less` pager? Extremely helpful for reading without having to look for the new line almost every time I scroll about half a page (press `d`).

```
-W or --HILITE‐UNREAD
       Like -w, but temporarily highlights the first new line after any
       forward movement command larger than one line.
```

**Comment by makew0rld** [comment]
I think this would be pretty tricky to achieve with the current architecture. I would still consider a PR for it however.

**Comment by makew0rld** [comment]
I am closing all stale non-bug issues so this issue will be closed. However a PR for this could still be accepted.
