### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by Carlo-Monte** [makew0rld/amfora#346]
Dear makew0rld, could you please make an up-to-date release? Many distributions only pack released versions, leading to them to not seeing the latest fixes. The diff towards v1.9.2 is not dramatic, but I am sure that it would be very nice to have.

Please see the discussion at an issue with the Alpine Amfora package: https://gitlab.alpinelinux.org/alpine/aports/-/issues/15741 , which is related to the Amfora Issue 343: https://github.com/makew0rld/amfora/issues/343 . 

Thank you so much.

**Comment by makew0rld** [comment]
v1.10.0 released!
