### ISSUE TITLE
Customise scroll amount

### ISSUE THREAD

**Issue by vext01** [makew0rld/amfora#348]
Hi,

I've just tried amfora for the first time today and one of the things I'm finding a bit jarring is that pagedown seems to only scroll the page about 50%.

I fired up nvim to see what I'm used to. By default it seems that a pagedown scrolls a whole screen minus 2 lines.

Would it be possible to allow customisation of `pgdn` somehow?

Cheers

**Comment by makew0rld** [comment]
I think this behaviour is by design, although the comment for the `pageDown` function says it's supposed to be 75%, not sure what's up there. You're welcome to change this in a PR however.
