### ISSUE TITLE
Removing a bookmark is impossible for unreachable URLs

### ISSUE THREAD

**Issue by doga** [makew0rld/amfora#350]
## 🪲 The bug

Some Gemini URLs become unreachable after having been bookmarked:

<img width="300" alt="Screenshot 2024-10-12 at 10 46 41" src="https://github.com/user-attachments/assets/faa6d7a7-4193-4cb2-8c74-4ad9a4e84506">

But `amfora` only allows "unbookmarking" when the user is already on the page to be "unbookmarked":

<img width="300" alt="Screenshot 2024-10-12 at 10 47 11" src="https://github.com/user-attachments/assets/e3c35309-79b5-4307-9109-359c773e0a4a">

## ✅ The fix

Allowing bookmarks to be removed directly from the `about:bookmarks` page would resolve this issue.

**Comment by doga** [comment]
> This is not a bug, only a missing feature. I would accept a PR for this.

This is clearly a bug. This type of failed support / misrepresentation of bug reports is the surest way of making `amfora` a legacy browser.

**Comment by makew0rld** [comment]
There is no dev team, only me. And Amfora is indeed a legacy browser. As [stated](https://github.com/makew0rld/amfora?tab=readme-ov-file#project-status) on the README, Amfora is in maintenance mode. Anyone is always welcome to fork it as long as they respect the license.

Note it's always possible to remove the bookmark by editing the bookmarks file, see [the wiki](https://github.com/makew0rld/amfora/wiki/Bookmarks).

**Comment by doga** [comment]
> There is no dev team, only me. And Amfora is indeed a legacy browser. As [stated](https://github.com/makew0rld/amfora?tab=readme-ov-file#project-status) on the README, Amfora is in maintenance mode. Anyone is always welcome to fork it as long as they respect the license.
> 
> Note it's always possible to remove the bookmark by editing the bookmarks file, see [the wiki](https://github.com/makew0rld/amfora/wiki/Bookmarks).

Thanks, I've seen your reply after having deleted my message. Is there another Gemini browser for the terminal that you can recommend?
