### ISSUE TITLE
Create links in plaintext

### ISSUE THREAD

**Issue by makew0rld** [makew0rld/amfora#54]
They should at least be accessible using <kbd>Tab</kbd>, aka link selection mode, but it would be nice to have links numbers for the URLs too, maybe in the left margin.

The links can be detected and made selectable using a regex. The regex should run after the page is rendered initially.

**Comment by makeworld-the-better-one** [comment]
Useful regex links
- https://mathiasbynens.be/demo/url-regex
- https://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url
- https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url

**Comment by makew0rld** [comment]
I am closing all stale non-bug issues so this issue will be closed. However a PR for this could still be accepted.
